r2013-02-18-tunr/config/routes.rb
R20130218Tunr::Application.routes.draw do
  root :to => 'home#index'
  resources :genres, :artists, :mixtapes
    resources :albums do
    member do
      get 'purchase'
      post 'buy'
    end
  end
  resources :songs do
    member do
      get 'purchase'
      post 'buy'
    end
  end
  resources :users, :except => [:edit] do
    collection do
      get 'edit'
    end
  end

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

r2013-02-18-tunr/app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :string(255)
#  filename   :string(255)
#  album_id   :integer
#  artist_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  price      :decimal(, )
#

class Song < ActiveRecord::Base
    attr_accessible :name, :image, :filename, :price, :album_id, :artist_id, :genre_ids
    belongs_to :album
    belongs_to :artist
    has_and_belongs_to_many :mixtapes
    has_and_belongs_to_many :genres
    validates :price, :presence => true, :numericality => { :greater_than => 0 }
    # validates :name, :presence => true, :uniqueness => true
end

r2013-02-18-tunr/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_filter :check_if_admin, :only => [:new, :create, :edit, :update]

  def index
    @songs = Song.order(:name)
  end
  def new
    @song = Song.new
  end
  def create
    @song = Song.new(params[:song])
    if @song.save
      redirect_to(songs_path)
    else
      render :new
    end
  end
  def edit
    @song = Song.find(params[:id])
    render :new
  end
  def show
    @song = Song.find(params[:id])
  end
  def update
    @song = Song.find(params[:id])
    if @song.update_attributes(params[:song])
      redirect_to(songs_path)
    else
      render :new
    end
  end
  def destroy
    @song = Song.find(params[:id])
    @auth.balance += (@song.price * 0.7)
    @auth.save
    @song.save

    song = Song.find(params[:id])
    song.delete
    redirect_to(songs_path)
  end

  def purchase
    @song = Song.find(params[:id])
  end
  def buy
    @song = Song.find(params[:id])
    @auth.balance -= @song.price
    @auth.save
    @song.save

    mixtape_ids = params[:song][:mixtape_ids]
    mixtape_ids.each do |id|
      mixtape = Mixtape.find(id)
      mixtape.songs << @song
    redirect_to(root_path)
    end
  end

end

r2013-02-18-tunr/app/views/songs/index.html.haml
#table
  %span= link_to('New Songs', new_song_path, :class => 'button radius success tiny') if is_admin
  %br
  %br
  %table
    - @songs.each do |song|
      -if song.name != nil
        %tr
          %td= link_to(song.name, song_path(song))
          %td= image_tag(song.image)
          -if is_admin
            %td= link_to('Edit', edit_song_path(song), :class => 'button radius standard tiny')
            %td= link_to('Delete', song, :method => :delete, :class => 'button radius alert tiny')
          %td= audio_tag(song.filename, :controls => true) if !@auth.nil?
          / %td
          /   -if @auth.mixtapes.map(&:songs).flatten.include?(song)
          /     =link_to('Song Purchased!', nil, :class => 'button disabled tiny alert')
          /   - else
          /     =link_to('Purchase Song', purchase_song_path(song.id), :method => 'get', :confirm => 'Are you sure?', :class => 'button radius

r2013-02-18-tunr/app/views/songs/new.html.haml
.row
  .five.columns
    = render(:partial => 'shared/errors', :locals => {:object => @song})
    = form_for @song do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = f.label :image
      = f.text_field :image
      = f.label 'File Name'
      = f.text_field :filename
      = f.label :price
      = f.text_field :price, :value => number_to_currency(f.object.price, :precision => 2)
      = f.select :artist_id, Artist.all.map{|artist| [artist.name, artist.id]}, :prompt => "Select an Artist"
      %br
      %br
      = f.select :album_id, Album.all.map{|album| [album.name, album.id]}, :prompt => "Select an Album"
      %br
      %br
      %strong Genres:
      %p
      -Genre.find(:all, :order => 'LOWER(name)').each do |genre|
        %span= check_box_tag "song[genre_ids][]", genre.id, genre.in?(@song.genres.to_a)
        %span= genre.name
        %p
      = f.submit nil, :class => 'button radius'
  .seven.columns

r2013-02-18-tunr/app/views/songs/purchase.html.haml
%h2 Purchase Confirmation
%h3= @song.name
%h5
  %span Performed by:
  %span= @song.artist.name
%p
  %strong Please select a Mixtape
= form_tag buy_song_path(@song)
-@auth.mixtapes.order(:name).each do |mixtape|
  =check_box_tag('song[mixtape_ids][]', mixtape.id)
  =mixtape.name
  %p
=button_to('Purchase', buy_song_path, :class => 'button radius')

r2013-02-18-tunr/app/views/songs/show.html.haml
%h2= @song.name
%div= image_tag(@song.image)
%br
%div= audio_tag(@song.filename, :controls => true) if !@auth.nil?
%br
%strong Album Name:
-if @song.album != nil
  = link_to(@song.album.name, album_path(@song.album.id))
%br
%br
%strong Artist Name:
-if @song.artist != nil
  = link_to(@song.artist.name, artist_path(@song.artist.id))
%br
%br
%strong Genres:
%ul
-if @song.genres != nil
  -@song.genres.each do |genre|
    %li= link_to(genre.name, genre_path(genre))
%br
-if @auth.present?
  %strong Purchase This Song:
  %br
  %br
  -if @auth.mixtapes.empty?
    .row
      .six.columns
        .alert-box
          You must create a Mixtape before purchasing this song
  -else
    -if @song.price > @auth.balance
      .row
        .three.columns
          .alert-box.alert
            Insufficient Funds
    -else
      %span= button_to(number_to_currency(@song.price), purchase_song_path, :method => :get, :confirm => "Are you sure you want to buy this song?", :class => 'button radius success')
-else
  %br