r2013-03-21-hacker-news/config/routes.rb
R20130321HackerNews::Application.routes.draw do
  root :to => 'home#index'
  post '/scrape' => 'scrape#scrape'
end

r2013-03-21-hacker-news/app/models/scrape.rb
class Scrape
  attr_accessor :pages, :current_page

  def initialize(pages)
    pages = 1 if pages == 0
    @pages = pages
    @current_page = 0
  end

  def get_data(path)
    if @current_page < @pages
      path = path[1..-1] if path.starts_with? '/'
      url = "https://news.ycombinator.com/#{path}"
      html = HTTParty.get(url)
      doc = Nokogiri::HTML(html)
      links = doc.css('.title > a')
      links[0..-2].each do |link|
        Story.create(:title => link.content, :url => link.get_attribute('href'))
      end

      @current_page += 1
      more = links.last.get_attribute('href')
      get_data(more)
    end
  end
end

r2013-03-21-hacker-news/app/models/story.rb
# == Schema Information
#
# Table name: stories
#
#  id         :integer          not null, primary key
#  title      :text
#  url        :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Story < ActiveRecord::Base
  attr_accessible :title, :url
end

r2013-03-21-hacker-news/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

r2013-03-21-hacker-news/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @stories = Story.all
  end
end

r2013-03-21-hacker-news/app/controllers/scrape_controller.rb
class ScrapeController < ApplicationController
  def scrape
    pages = params[:pages].to_i
    Story.delete_all
    scraper = Scrape.new(pages)
    scraper.get_data('news')
    @stories = Story.all
  end
end

r2013-03-21-hacker-news/app/helpers/application_helper.rb
module ApplicationHelper
end

r2013-03-21-hacker-news/app/views/home/index.html.haml
.row
  .large-1.columns
    = form_tag scrape_path, :remote => true do
      = text_field_tag 'pages', nil, :autofocus => true
.row
  .large-2.columns
    = label_tag 'Number of Pages'
    = submit_tag 'Scrape', :id => 'submit_btn', :class => 'button success radius'
  .large-9.columns

#stories
  = render :partial => 'shared/stories'

r2013-03-21-hacker-news/app/views/shared/_stories.html.haml
%ol
  - @stories.each do |story|
    %li= link_to(story.title, story.url, :target => '_blank')